# Generated by Django 5.0.1 on 2024-02-04 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0002_diposite_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diposite',
            name='balance_after_borrowed',
            field=models.DecimalField(decimal_places=2, max_digits=12, null=True),
        ),
    ]
