# Generated by Django 5.0.1 on 2024-02-06 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_useraccount_image'),
        ('transaction', '0003_alter_diposite_balance_after_borrowed'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Diposite',
            new_name='Transaction',
        ),
    ]
