# Generated by Django 5.0.1 on 2024-02-03 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_useraccount_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='accounts/media/profile/'),
        ),
    ]
