# Generated by Django 5.0.1 on 2024-02-06 14:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_useraccount_image'),
        ('book', '0005_alter_bookreview_review'),
    ]

    operations = [
        migrations.CreateModel(
            name='BorrowBooK',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('borrowDate', models.DateTimeField(auto_now_add=True)),
                ('borrowBook', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book.book')),
                ('borrowUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.useraccount')),
            ],
        ),
    ]
