# Generated by Django 5.0.1 on 2024-02-06 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0008_book_account_alter_borrowbook_borrowuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookreview',
            name='review',
            field=models.TextField(),
        ),
    ]
